### PR TITLE
set destination directory inside jar that assets will go in

### PR DESCRIPTION
**Pull request by nitay**
@mateor here's first small change I made to get webpack to work on our codebase. Not familiar with your process at foursquare so lmk what you want me to do PR wise.

### CODE REVIEW

**Comment by mateor** [comment]
Hi nitay

I will give this a shot between now and early next week. I am also going to try and configure fsqio to publish sdists so that you will have a path to remove the inlined code from your repo once we land any tweaks like this you need. I will respond when I get there, thanks for posting it!

**Comment by nitay** [comment]
sg, thx @mateor

**Comment by mateor** [comment]
This has been merged into Fsq.io. Sorry for the long delay - we were blocked internally with bugs in upstream Pants. Consuming Pants 1.2.1 finally allowed the upgrade to stick.

I have lots of code slated to roll out to Fsq.io now that we are in rough parity with upstream, but this commit is already live. 

I hope to configure Fsq.io  to publish the webpack plugin as an sdist at some point soon, but for now it is still only available as loose source.

**Comment by mateor** [comment]
https://github.com/foursquare/fsqio/commit/f1cc586aff7559fbcf0a2d80ce97f43c4f18a33f

**Comment by nitay** [comment]
awesome, thx @mateor

**Pull request closed without merging**
